apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: qotd-clone
  labels:
    sandbox: learn-pipelines
    learn-pipelines: pipeline
spec:
  workspaces:
  - name: shared-workspace
  params:
  - name: git-url
    type: string
    description: url of the git repo for the code of deployment
    default: https://github.com/redhat-developer-demos/qotd.git
  - name: IMAGE
    type: string
    description: image to be built from the code
    default: image-registry.openshift-image-registry.svc:5000/pipelines-tutorial/qotd:latest
  tasks:
  - name: fetch-repository
    taskRef:
      resolver: git
      params:
      - name: url
        value: https://github.com/tektoncd/catalog.git
      - name: pathInRepo
        value: task/git-clone/0.4/git-clone.yaml
      - name: revision
        value: main
    workspaces:
    - name: output
      workspace: shared-workspace
    params:
    - name: url
      value: $(params.git-url)
    - name: subdirectory
      value: ""
    - name: deleteExisting
      value: "true"
