apiVersion: tekton.dev/v1beta1 
kind: Pipeline 
metadata:
  name: qotd-build-and-deploy
  labels:
    sandbox: learn-pipelines
    learn-pipelines: pipeline 
spec: 
  workspaces: 
  - name: shared-workspace
  params: 
  - name: git-url
    type: string
    description: url of the git repo for the code of deployment
    default: https://github.com/redhat-developer-demos/qotd.git
  - name: IMAGE
    type: string
    description: image to be built from the code
    default: image-registry.openshift-image-registry.svc:5000/pipelines-tutorial/qotd:latest
  tasks: 
  - name: fetch-repository
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-workspace
    params:
    - name: url
      value: $(params.git-url)
    - name: subdirectory
      value: ""
    - name: deleteExisting
      value: "true"
  - name: build-image 
    taskRef:
      name: buildah
    params:
    - name: TLSVERIFY
      value: "false"
    - name: IMAGE
      value: $(params.IMAGE)
    workspaces:
    - name: source
      workspace: shared-workspace
    runAfter:
    - fetch-repository
  - name: apply-manifests 
    taskRef:
      name: apply-manifests
    workspaces:
    - name: source
      workspace: shared-workspace
    runAfter: 
    - build-image
